import { IProduto } from "../dtos/IProduto";

const PRODUCTS_DATA: IProduto[] = [
  {
    produto_id: 1,
    nome: "Notebook Dell Inspiron",
    categoria: "Eletrônicos",
    possuiValidade: false,
    estoque: 20,
    status: true,
  },
  {
    produto_id: 2,
    nome: "Tênis Nike Air Max",
    categoria: "Moda",
    possuiValidade: false,
    estoque: 50,
    status: true,
  },
  {
    produto_id: 3,
    nome: "Cadeira de Escritório Ergonômica",
    categoria: "Móveis",
    possuiValidade: false,
    estoque: 10,
    status: true,
  },
  {
    produto_id: 4,
    nome: "Smartphone Samsung Galaxy S21",
    categoria: "Eletrônicos",
    possuiValidade: false,
    estoque: 15,
    status: true,
  },
  {
    produto_id: 5,
    nome: "Livro: O Senhor dos Anéis",
    categoria: "Livros",
    possuiValidade: false,
    estoque: 30,
    status: true,
  },
  {
    produto_id: 6,
    nome: "Camisa Polo Lacoste",
    categoria: "Moda",
    possuiValidade: false,
    estoque: 25,
    status: true,
  },
  {
    produto_id: 7,
    nome: "Mesa de Jantar de Madeira",
    categoria: "Móveis",
    possuiValidade: false,
    estoque: 12,
    status: true,
  },
  {
    produto_id: 8,
    nome: "Câmera Fotográfica Canon EOS",
    categoria: "Eletrônicos",
    possuiValidade: false,
    estoque: 8,
    status: true,
  },
  {
    produto_id: 9,
    nome: "Chocolate Amargo Lindt",
    categoria: "Alimentos",
    possuiValidade: true,
    estoque: 40,
    status: true,
  },
  {
    produto_id: 10,
    nome: "Café em Grãos Especial",
    categoria: "Alimentos",
    possuiValidade: true,
    estoque: 35,
    status: true,
  },
  {
    produto_id: 11,
    nome: "Fones de Ouvido Apple AirPods",
    categoria: "Eletrônicos",
    possuiValidade: false,
    estoque: 18,
    status: true,
  },
  {
    produto_id: 12,
    nome: "Mala de Viagem Samsonite",
    categoria: "Moda",
    possuiValidade: false,
    estoque: 22,
    status: true,
  },
  {
    produto_id: 13,
    nome: "Sofá Retrátil e Reclinável",
    categoria: "Móveis",
    possuiValidade: false,
    estoque: 14,
    status: true,
  },
  {
    produto_id: 14,
    nome: "Notebook Apple MacBook Pro",
    categoria: "Eletrônicos",
    possuiValidade: false,
    estoque: 10,
    status: true,
  },
  {
    produto_id: 15,
    nome: "Vinho Tinto Reserva",
    categoria: "Alimentos",
    possuiValidade: true,
    estoque: 20,
    status: true,
  },
];

export default PRODUCTS_DATA;
